### ISSUE TITLE
Doesn't work with Krnl for some reason.

### ISSUE THREAD

**Issue by FFrutz** [lolmanurfunny/Roblox-Launcher-minus-the-app#30]
"Unable to find Roblox process", it says. Only when I use this launcher too.

**Comment by Zoardedz** [comment]
open task manager, check if RobloxPlayerBeta.exe is in there, if it is krnl should work, if not it won't

**Comment by FFrutz** [comment]
Obviously I have Roblox open, otherwise I wouldn't be writing this...

**Comment by FFrutz** [comment]
And yes, I did go to properties and it said RobloxPlayerBeta.

**Comment by CJStyles123** [comment]
ask your exploit developer, works fine for me and I'm using Synapse X.

**Comment by lolmanurfunny** [comment]
> I'm using Synapse X.

mf showing no mercy on a krnl user.

**Comment by FFrutz** [comment]
> ask your exploit developer, works fine for me and I'm using Synapse X.

Krnl devs have entire systems built around avoiding support it's kinda funny too lol

**Comment by lolmanurfunny** [comment]
Don't open new issues about exploits having incompatibility issues with this launcher, please. If it works for people who don't use exploits, that's great, that's why I developed this launcher, if it works for some exploits, cool, it is what it is, if it doesn't work for other exploits, I dnc/idgaf, it is what it is and it's not my problem. Opening an issue about a 3rd party software not working with another 3rd party software is goofy; that's conceptually similar to a mod developer being asked to add compatibility for another mod.

**Comment by FFrutz** [comment]
This is true, and I also just found a fix about 10 mins ago.
