### ISSUE TITLE
What would the (soon) new Anti-Cheat do to users of this custom launcher?

### ISSUE THREAD

**Issue by Paindeluxe** [lolmanurfunny/Roblox-Launcher-minus-the-app#47]
I am kind of afraid that the (soon) new Anti-Cheat could false detect this launcher as a Cheat yes I am acting like a conspiracy theorist since the source code is right here and it’s nothing bad but worrying about a issue never hurts

**Comment by Zoardedz** [comment]
i dont think it would have to do anything with this since the anti cheat should be strapped onto robloxplayerbeta and not robloxplayerlauncher, it would make sense if they strapped the anticheat from the robloxplayer though, but the smart decision would be robloxplayerbeta. and if roblox decides ever to stop file replacements then they would have to do something called file integrity verification

**Comment by lolmanurfunny** [comment]
> I am kind of afraid that the (soon) new Anti-Cheat could false detect this launcher as a Cheat yes I am acting like a conspiracy theorist since the source code is right here and it’s nothing bad but worrying about a issue never hurts

Likely nothing. We're at far less anti-cheat risk than rbxfpsunlocker is, though this might be an unfair comparison, though my point still stands.

> i dont think it would have to do anything with this since the anti cheat should be strapped onto robloxplayerbeta and not robloxplayerlauncher

Exactly what I would've said had you not commented before me.
