### ISSUE TITLE
can't join own private server

### ISSUE THREAD

**Issue by VoiderzX** [lolmanurfunny/Roblox-Launcher-minus-the-app#53]
![image](https://user-images.githubusercontent.com/114313973/196055530-6013539b-b870-48be-9b92-bf4406dd8f7b.png)

Idk if just me but i cant join my own private server but i can join other games

**Comment by Paindeluxe** [comment]
That can’t be a problem of the Launcher given that you are already logged into your account therefore is it a issue with Roblox itself

_Am I pulling this out of my ass? Hopefully not_

1. You were logged in on the Roblox website and also joined via the website, the website tells the Launcher something about which account it is trying to join the server.
2. As you are logged in on the website, the launcher doesn’t have to confirm if you are on the right account since it trusts the website.

**Comment by Zoardedz** [comment]
this could be a paramater from the roblox launcher that gets passed onto robloxplayerbeta which causes this, ill try doing this myself and comparing the join in paramaters with the custom launcher one

**Comment by Zoardedz** [comment]
update: its an issue from your side, i tried joining into my private server and it works fine :trollface:

**Comment by VoiderzX** [comment]
> update: its an issue from your side, i tried joining into my private server and it works fine :trollface:

yeah roblox glitch

**Comment by VoiderzX** [comment]
> That can’t be a problem of the Launcher given that you are already logged into your account therefore is it a issue with Roblox itself
> 
> _Am I pulling this out of my ass? Hopefully not_
> 
> 1. You were logged in on the Roblox website and also joined via the website, the website tells the Launcher something about which account it is trying to join the server.
> 2. As you are logged in on the website, the launcher doesn’t have to confirm if you are on the right account since it trusts the website.

roblox glitch but thanks for the help

**Comment by localfossa** [comment]
![image](https://user-images.githubusercontent.com/74490107/197290421-781a74c1-cf83-4489-bd99-ae5d13277cf2.png)
Roblox added this unnecessary setting. Set it as everyone.
